# Generated by Django 4.2.1 on 2023-08-08 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardname', models.CharField(max_length=30)),
                ('cardimg', models.ImageField(upload_to='pics')),
                ('cardprofession', models.CharField(max_length=30)),
                ('infoimg', models.ImageField(upload_to='pics/info')),
                ('infoname', models.CharField(max_length=30)),
                ('infoprofession', models.TextField()),
                ('infolocation', models.CharField(max_length=30)),
                
            ],
        ),
    ]
