# Generated by Django 4.2.1 on 2023-08-08 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MedEase', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='doctype',
            field=models.TextField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
