# Generated by Django 4.2.1 on 2023-08-08 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MedEase', '0002_doctor_doctype'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='infomail',
            field=models.EmailField(default=0, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctor',
            name='infophone',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
    ]
